name: windows編譯
on: push

jobs:
  build_to_exe:
    runs-on: windows-latest
    steps:
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src
